# Generated by Django 5.2.14 on 2026-06-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('speaker', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('series', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('fb_url', models.URLField(blank=True, help_text='Paste the Facebook video URL here', max_length=500)),
                ('youtube_id', models.CharField(blank=True, help_text='YouTube Video ID only e.g. dQw4w9WgXcQ', max_length=20)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='sermons/thumbnails/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sermon',
                'verbose_name_plural': 'Sermons',
                'ordering': ['-date'],
            },
        ),
    ]
